version: '3.8'

services:
  maywifin:
    build: .
    container_name: maywifin
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - ./db:/app/db
      - /app/node_modules
      # MONTEZ VOTRE MUSIQUE ICI (Host Path : Container Path)
      # Exemple: - /home/maywix/music:/music
      # - /VOTRE/CHEMIN/MUSIQUE:/music
    environment:
      - PORT=3000
    restart: unless-stopped
